import type { Metadata } from "next";
import { Geist, Geist_Mono ,DM_Sans, Montagu_Slab} from "next/font/google";
import "./globals.css";
import Header from "./_layout/Header";
import Footer from "./_layout/Footer";
import ProviderClient from "@/provider/ProviderClient";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const dmSans = DM_Sans({
  variable: "--font-dmSans",
  subsets: ["latin"],
});

const montagu = Montagu_Slab({
  variable: "--font-montagu",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${dmSans.variable} ${montagu.variable} font-montagu font-inter antialiased`}
      >
        <ProviderClient>
        <Header/>
        {children}
        <Footer/>
        </ProviderClient>
      </body>
    </html>
  );
}
